baseURL = "cv/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cv-almeida"

[params]
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorPageBackground = "#ddd"
colorRightColumnBackground = "#f5f5f5"
